/// The three kinds of QR code the attendee scanner understands, plus a fallback
/// for anything else the camera picks up.
///
/// Everything the gamification loop needs travels through a QR code:
///
/// | Kind | Payload | Action |
/// |---|---|---|
/// | [QrCheckinToken] | opaque token (not a URL) | `POST /checkin` |
/// | [QrPeerProfile] | `https://<host>/u/{profileRef}` | pair up, list the event's challenges |
/// | [QrVerifyCompletion] | `https://<host>/qr/verify/{completionId}` | `POST /challenge-completions/{id}/verify` |
///
/// Matching is done on the **path only**. `Environment.shareHost` is
/// `kolabing.com` in prod and a `laravel.cloud` host in dev, so keying off the
/// host would make every dev build fail to read a prod QR (and vice versa).
library;

/// Path segment that marks a peer-profile QR (`/u/{profileRef}`).
const String _peerSegment = 'u';

/// Path segments that mark a challenge-verification QR (`/qr/verify/{id}`).
const String _verifyFirstSegment = 'qr';
const String _verifySecondSegment = 'verify';

/// A check-in token is opaque base64url-ish text. The bounds keep obviously
/// unrelated QR codes (a URL, a phone number, a wifi payload) from being POSTed
/// to `/checkin`, while staying permissive enough that a backend token-format
/// change does not break check-in. The server is still the authority — an
/// accepted-here-but-invalid token just comes back as a 404.
final RegExp _checkinTokenPattern = RegExp(r'^[A-Za-z0-9_\-=]{12,256}$');

/// A scanned QR code, resolved to the action it should trigger.
sealed class QrPayload {
  const QrPayload();

  /// Classifies [raw] — the exact string the camera decoded.
  ///
  /// Never throws: anything unrecognised comes back as [QrUnknown] so the
  /// scanner can show a localized "unrecognised code" message and keep going.
  static QrPayload parse(String raw) {
    final value = raw.trim();
    if (value.isEmpty) return QrUnknown(raw);

    final uri = Uri.tryParse(value);
    final isWebUrl =
        uri != null && (uri.scheme == 'http' || uri.scheme == 'https');

    if (isWebUrl) {
      final segments = uri.pathSegments
          .where((s) => s.isNotEmpty)
          .toList(growable: false);

      if (segments.length == 2 &&
          segments[0].toLowerCase() == _peerSegment) {
        return QrPeerProfile(segments[1]);
      }

      if (segments.length == 3 &&
          segments[0].toLowerCase() == _verifyFirstSegment &&
          segments[1].toLowerCase() == _verifySecondSegment) {
        return QrVerifyCompletion(segments[2]);
      }

      // A URL we recognise the shape of but not the route — never a token.
      return QrUnknown(raw);
    }

    if (_checkinTokenPattern.hasMatch(value)) {
      return QrCheckinToken(value);
    }

    return QrUnknown(raw);
  }
}

/// An event check-in token, generated by the organizer via
/// `POST /events/{event}/generate-qr` and displayed on `EventQRCodeScreen`.
final class QrCheckinToken extends QrPayload {
  const QrCheckinToken(this.token);

  final String token;

  @override
  String toString() => 'QrCheckinToken(${token.length} chars)';
}

/// Another attendee's profile QR — the one shown by the "My QR" sheet.
///
/// [profileRef] is the universal profile id, or the `@handle` when the profile
/// id is unavailable (see `AttendeeMainScreen`'s My-QR sheet).
final class QrPeerProfile extends QrPayload {
  const QrPeerProfile(this.profileRef);

  final String profileRef;

  @override
  String toString() => 'QrPeerProfile($profileRef)';
}

/// A challenge completion awaiting this scanner's verification.
final class QrVerifyCompletion extends QrPayload {
  const QrVerifyCompletion(this.completionId);

  final String completionId;

  @override
  String toString() => 'QrVerifyCompletion($completionId)';
}

/// Anything the scanner does not understand.
final class QrUnknown extends QrPayload {
  const QrUnknown(this.raw);

  final String raw;

  @override
  String toString() => 'QrUnknown';
}
